### ISSUE TITLE
Non-configurable AttributeListEncoder elements delimiter 

### ISSUE THREAD

**Issue by vesurbag** [pdvrieze/xmlutil#111]
**Data class:**
```
@Serializable
data class Example(
    @XmlElement(false)
    val languages: List<String> = listOf("en", "es")
)
```

**Actual behavior:**
`<Example languages="en es"/>`

Is it possible to make delimiter configurable at [this](https://github.com/pdvrieze/xmlutil/blob/master/serialization/src/commonMain/kotlin/nl/adaptivity/xmlutil/serialization/XMLEncoder.kt#L870) part? 

**Expected behavior:**
`<Example languages="en,es"/>`

**Comment by pdvrieze** [comment]
I've added this to [0.85.0](https://github.com/pdvrieze/xmlutil/releases/tag/v0.85.0).
