### ISSUE TITLE
Validation xs:choice

### ISSUE THREAD

**Issue by SchweinchenFuntik** [pdvrieze/xmlutil#115]
Is it possible to make schema validation for xs:choice (it is possible not only for it)

**Comment by pdvrieze** [comment]
As a separate project I'm working on XmlSchema support, but as xml schema is actually quite complex it will take a while. In any case it would be a separate library (but I would allow integration somehow). The main application would be to generate schemas from serializers or classes from a schema.

Looking at your query you're more interested in validation of values. The values are effectively part of the class invariants. I would say you should implement the validation as part of the object's constructor. This means that the object will meet its invariants in all cases, not only when deserialized. Such validation would also be generally a part of the serialization library itself, but I don't see how this would be done in general.

**Comment by SchweinchenFuntik** [comment]
Thank you. As for reading the schema, I'm also interested, since I just rely on the external XML Scheme, and write my classes.
Let me know when you can watch
