### ISSUE TITLE
A problem about HTML tag

### ISSUE THREAD

**Issue by OrientLegend** [pdvrieze/xmlutil#117]
Some HTML tags are not self-closing, even if they are parsed with "CompactFragment", there will still be problems.
For example:
```xml
<content type="html">
<img src="...">
</content>
```
If I parse the above xml, then an error occured, "expected: /img read: content".
What should I do?

**Comment by pdvrieze** [comment]
Unfortunately there is no way to parse regular HTML without having HTML specific knowledge. This is one of the reasons why the xhtml serialization is still valuable. As this library is for xml and serialization it is not intended to support reading html (html parsers are not that straightforward, especially when considering the error handling behaviour they are expected to have - they should handle invalidly nested tags gracefully).

Your "xml" is not actually xml as a lack of end tag makes it invalid. Most xml parsers will/should fail to parse it.

If you have the option, I would go with the following in order of elegance:
- Use xhtml (with namespace declarations). This is a valid way in which html can be serialized in a way that is compatible with xml, and as long as the xml generated doesn't use entities in weird ways (never generated by this library) is understood by html parsers as well.
- If you have to deal with html, treat it as opaque strings with escaping (either entities or as CDATA sections)
- Deal with it as binary data (using for example base64 encoding)
- When creating the xml document use an html-to-xhtml translator (for example read it in to dom, then serialize it to xhtml). Note that the serialization will generate xml/xhtml, and while you can put html in a compactfragment this will probably fail when serializing (it is actually parsed to xml events to handle namespaces, not merely dumped).
