### ISSUE TITLE
Broken output when Encoding specific Codepoints

### ISSUE THREAD

**Issue by Shamicen** [pdvrieze/xmlutil#121]
Encoding ⚠️`\u{26a0}\u{fe0f}` outputs the ⚠`\u{26a0}` character followed by a broken `NULL` character.

Input:
![Input](https://user-images.githubusercontent.com/84282253/220125340-59457236-fabf-49bb-9c5c-a98037a1f08f.jpg)

Output when read back in with xmlutil:
![Output_when_read_by_xmlutil](https://user-images.githubusercontent.com/84282253/220125499-d21e67f6-0e72-473c-8435-cf73185d8fe0.jpg)

Output when read with the Android Studio file browser:
![Output_in_Android Studio](https://user-images.githubusercontent.com/84282253/220125680-665f1a81-d75a-465f-ba22-8e5e8e7e962e.jpg)

**Comment by pdvrieze** [comment]
I've just fixed it in dev. The platform independent writer mistakenly doesn't work with values between `0xE000` and `0xFFFD`.
