### ISSUE TITLE
Cannot deserialize XML containing xml:space in 0.85.0 (worked in 0.84.3)

### ISSUE THREAD

**Issue by yuriykulikov** [pdvrieze/xmlutil#122]
Given XML like this:

```
...
<L-5 L="EN" xml:space="default">some text</L-5>
...
```

And Kotlin code like this:

```
const val xml = "http://www.w3.org/XML/1998/namespace"
@Serializable
data class L5(
    @SerialName("L") val l: String,
    @XmlValue(true) val value: String,
    @XmlSerialName("space", xml, "") val space: String,
)
```

Deserialization fails due to

`kotlinx.serialization.MissingFieldException: Field 'space' is required for type with serial name 'xml.L5', but it was missing`

This was working in 0.84.3, but not in 0.85.0

**Comment by yuriykulikov** [comment]
After reading release notes more carefully, I have removed `@XmlSerialName("space", xml, "") val space: String,` and it solved the issue. It seems that `space` is treated in a special way since https://github.com/pdvrieze/xmlutil/commit/c402b3ba732aa49904893a46431642e6c373c5f0

**Comment by pdvrieze** [comment]
@yuriykulikov Sorry for breaking things. But indeed I added support for handling the xml:space attribute.

**Comment by yuriykulikov** [comment]
All good, the adjustment was quick after reading release notes and commit messages 🙂

**Comment by pdvrieze** [comment]
I've updated the dev branch to support explicit attributes (and not hide them) - only attributes though (it is illegal in xml to have it as an element).
