### ISSUE TITLE
Inconsistent behavior for event type IGNORABLE_WHITESPACE in XmlReader

### ISSUE THREAD

**Issue by sschirr** [pdvrieze/xmlutil#128]
Newline characters after a starting element and followed by another starting element will be detected as event type TEXT on most platform targets (native, android, js). Only on the jvm target it is (correctly) detected as a IGNORABLE_WHITESPACE.

I implemented a test for this case that is only passing on jvm target. See: #127

**Comment by pdvrieze** [comment]
The parser is schemaless and technically ignorable whitespace can only be determined in the context of a schema (technically only when there can not be values is the whitespace ignorable).
