### ISSUE TITLE
Provide a way to further customize XML output for serialization plugin

### ISSUE THREAD

**Issue by altavir** [pdvrieze/xmlutil#13]
I believe, it is possible via custom XMLWriter, but I did not manage to find a simple way to do it.

What I want is to provide XML without closing tags for elements without children. But probably there are other options that could be moved to the top level.

**Comment by pdvrieze** [comment]
The option for selfclosing tags for empty elements is indeed a property of the underlying writer. Not only that, but different implementations behave differently on this (and may or may not support it). In StAX it can be done by setting some property, but it depends on the actual engine (I like woodstox - the one built into jdk8 at least is buggy for this kind of stuff).

I will try what I can do in the multiplatform support to add "request..." options. I cannot provide a guarantee as it relies on the capabilities of the underlying engines. It is possible already, but it is not multiplatform. For the JVM what you do is create a regular stax based writer and wrap it in `StaxWriter`. This is the default implementation for JVM.

If you want to do it in bulk, you could provide your own factory to `XmlStreaming`. This uses service loaders under water to provide different implementations. It has a `setFactory` method that you can use to make it use your own factory (of course Stax itself uses another service loader).

**Comment by pdvrieze** [comment]
This is a limitation of the standard xml writer included in the JVM. Woodstox can for example do this better.

**Comment by pdvrieze** [comment]
I may consider using the android serializer (which is a forked version of the serializer in the android source code) throughout the entire project. This serializer however does not validate the output.
However, since rervision b6cea5b it should work on stax through deferring the writing of the start tag until either an end tag is present or content is requested.
