### ISSUE TITLE
Is there a way to parse a generic xml  ?

### ISSUE THREAD

**Issue by jbruchanov** [pdvrieze/xmlutil#137]
I'm trying to read a random xml doc with unknown structure.
Is there a way to parse it to some generic XmlElement object which I can just traverse manually ?

**Comment by pdvrieze** [comment]
Yes there is. The base xmlutil-core module does this. It provides pull parser/generators though the XmlStreaming interface. There is also support for DOM (there are some bugs fixed in dev), a custom implementation on native and reusing the platform ones on js/jvm/android.

**Comment by pdvrieze** [comment]
In addition there are NodeSerializer and ElementSerializer that allow Dom and serialization to be mixed (like JsonElement)

**Comment by jbruchanov** [comment]
@pdvrieze 
can you please ping me a code snippet or if there is a test/example how to do it ?

**Comment by jbruchanov** [comment]
thanks a lot...
