### ISSUE TITLE
Repeated element types are ignored by default if kotlin property is not a list.

### ISSUE THREAD

**Issue by mgroth0** [pdvrieze/xmlutil#145]
If I am deserializing an XML file that has repeated element types, I can set the kotlin property to either be a single instance or a list. 

In kotlin, I can use:
```kotlin
@Serializable
@XmlSerialName("Track", NAMESPACE_VSTD, PREFIX_VSTD)
class Track(
    val frameAnnotations: FrameAnnotation
)
```

or

```kotlin
@Serializable
@XmlSerialName("Track", NAMESPACE_VSTD, PREFIX_VSTD)
class Track(
    val frameAnnotations: List<FrameAnnotation>
)
```

Both of the above serializable classes can be used to deserialize the XML file without any error being thrown. However, the first one silently ignores the repeated elements. This is an issue when I need to make sure I am not ignoring any data.

The default configuration throws exceptions if an element in the XML is not found in the serializable class. Therefore, users are made to epect that this library ensures data is not being ignored. However, in this case it is.

Is there a configuration option that can make it so errors are thrown when a repeated element is found but the property is not set as a list? And if so, perhaps this should be enabled by default.

**Comment by pdvrieze** [comment]
Now released as 0.86.1
