### ISSUE TITLE
ways to get rid of "Expected text content or end tag, found: START_ELEMENT"

### ISSUE THREAD

**Issue by chumpa** [pdvrieze/xmlutil#146]
I have some xml and xmlutil-based parser for it. Default policy is used, the data model is simple enough (sometimes CompactFragment is used). But for some giant well-formed XMLs I got an error "Expected text content or end tag, found: START_ELEMENT".

My assumption by prev experience is I described some element as 1..1 but in fact in giant XML there are 1..unbounded occurences.
Of course I can split giant into pieces and manually discover the bug, but wondering if there any advice how to do it more smart?

**Comment by chumpa** [comment]
I have understood the reason using stacktrace. That's clear.

**Comment by bqv** [comment]
This is extremely inconvenient, why doesn't it show where the error is?

Even just byte position would be fine, but I see "Invalid XML value at position: null"

**Comment by pdvrieze** [comment]
@bqv Your error seems different than the original one. The stacktrace may help understand why the position is null (note though that it requires the xml parser to provide the location) - note that this message is for an `XmlParsingException` which is mainly used to wrap other exceptions and add location information - it provides the original as cause. Which parser/reader are you using?
