### ISSUE TITLE
Parsing failed on XML with schema

### ISSUE THREAD

**Issue by altavir** [pdvrieze/xmlutil#15]
If I have a XML file like this: 
```xml
<?xml version="1.0"?>
<gdml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://service-spi.web.cern.ch/service-spi/app/releases/GDML/schema/gdml.xsd">
```
The parsing is failed with message: 
```
nl.adaptivity.xmlutil.serialization.UnknownXmlFieldException: Could not find a field for name {http://www.w3.org/2001/XMLSchema-instance}noNamespaceSchemaLocation
```

**Comment by pdvrieze** [comment]
I'll have a look at the best way to achieve this, but I'm thinking of primarily using an annotation for this. To me it feels like a property of the data structure, not the parser instance.

**Comment by pdvrieze** [comment]
Master now has a configuration option for a callback that is called when an attribute/tag can not be matched to a field. This can be used to ignore as desired.
