### ISSUE TITLE
Setting nilAttribute configuration to xsi:nil="true" results in sequence order of element not be preserved

### ISSUE THREAD

**Issue by frenchmb** [pdvrieze/xmlutil#152]
We have the following configuration for the XML parser:

nilAttribute = qname(Namespaces.XmlSchemaInstance, "nil", Prefixes.XmlSchemaInstance) to "true"

When we serialize a class the order of the element is not preserved when an element is null:

`
<Parameters>
                    <IgnoreLimitWarningsArray xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
                    <ExecutionInstructionsArray xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
                    <ExecutionInstructionsDictionaryArray xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
                    <ExecutionInstructionsRestatedArray xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
                    <ClientSequenceNumberArray xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
                    <CustomColumnsArray xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
                    <CustomColumnsRestatedArray xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
                    <TradingPassword xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
                    <OrderNumberArray>
                        <OrderNumber>138084514</OrderNumber>
                    </OrderNumberArray>
                </Parameters>
`

All the nil elements are placed at the top which is not the correct definition of sequence order:

`@Serializable
@XmlSerialName(value = "Parameters")
class OrderDelete (
    @XmlElement
    @XmlSerialName("OrderNumberArray")
    @XmlChildrenName("OrderNumber", namespace = "http://webservices.iress.com.au/v4/")
    val orderNumberArray: List<String>,

    @XmlElement
    @XmlSerialName("IgnoreLimitWarningsArray")
    @XmlChildrenName("IgnoreLimitWarnings", namespace = "http://webservices.iress.com.au/v4/")
    val ignoreLimitWarningsArray: List<Boolean>? = null,

    @XmlElement
    @XmlSerialName("ExecutionInstructionsArray")
    @XmlChildrenName("ExecutionInstructions", namespace = "http://webservices.iress.com.au/v4/")
    val executionInstructionsArray: List<String>? = null,

    @XmlElement
    @XmlSerialName("ExecutionInstructionsDictionaryArray")
    val executionInstructionsDictionary: List<IressDictionary>? = null,

    @XmlElement
    @XmlSerialName("ExecutionInstructionsRestatedArray")
    @XmlChildrenName("ExecutionInstructionsRestated", namespace = "http://webservices.iress.com.au/v4/")
    val executionInstructionsRestatedArray: List<Boolean>? = null,

    @XmlElement
    @XmlSerialName("ClientSequenceNumberArray")
    @XmlChildrenName("ClientSequenceNumber", namespace = "http://webservices.iress.com.au/v4/")
    val clientSequenceNumberArray: List<Long>? = null,

    @XmlElement
    @XmlSerialName("CustomColumnsArray")
    @XmlChildrenName("CustomColumns", namespace = "http://webservices.iress.com.au/v4/")
    val customColumnsArray: List<String>? = null,

    @XmlElement
    @XmlSerialName("CustomColumnsRestatedArray")
    @XmlChildrenName("CustomColumnsRestated", namespace = "http://webservices.iress.com.au/v4/")
    val customColumnsRestatedArray: List<Boolean>? = null,

    @XmlElement
    @XmlSerialName("TradingPassword")
    val tradingPassword: String? = null,
)`

Unfortunately the SOAP service we are integrating to requires the order to be preserved.  Is the away to fix this?

**Comment by pdvrieze** [comment]
This is actually the result of a bug that could also cause crashes if tag children exist before attributes. This should now be fixed in dev (and the automatically generated snapshot release).
