### ISSUE TITLE
ERROR: PI must start with XML

### ISSUE THREAD

**Issue by Lawrance3** [pdvrieze/xmlutil#155]
I'm using your XML library and I'm running into an issue where I'm receiving the error "PI must start with XML". This issue arises when I'm trying to parse an XML document that starts with a Byte Order Mark (BOM).

The XML document that I'm trying to parse is encoded in UTF-8 and it starts with a BOM. It seems like the parser is misinterpreting the BOM as part of the XML declaration and causing the error.

**Comment by pdvrieze** [comment]
@Lawrance3 Technically utf-8 does not need a byte order mark (it is irrelevant for utf-8 as it is in stream order, not machine word order - BOM's are for UTF-16, it is not recommended to do this in the standard). It is worth noting that there are multiple parsers that could be used. I've fixed both the platform independent reader (always used for native) and the dom reader (for JS). They will  now ignore an initial BOM (note that both work on UFT-16 readers, so an inverted BOM should certainly never happen - a BOM shouldn't actually happen as BOM's should be handled in UTF-8 to reader/charsequence conversion.
