### ISSUE TITLE
Need Wasm target

### ISSUE THREAD

**Issue by sgopi93** [pdvrieze/xmlutil#157]
It would be great if we support wasm target

**Comment by pdvrieze** [comment]
Will be added once supported by a stable version of the Kotlin compiler.

**Comment by ZacSweers** [comment]
Does it need to wait for a stable release? You could mark it as experimental in release notes since it's also experimental (and requires opt-in) in kotlin

**Comment by pdvrieze** [comment]
@ZacSweers I'll add it once support is integrated into kotlinx.serialization proper (may experimentally), unless someone helps making the build system work with the alternative source for the wasm dependencies. It doesn't need to be stable, it can be experimental, but it should be able to be built as part of the standard build process.

**Comment by StefanOltmann** [comment]
@pdvrieze It looks like that `kotlinx.serialization` finally got WASM support.

https://github.com/Kotlin/kotlinx.serialization/releases

**Comment by pdvrieze** [comment]
@StefanOltmann It should be available as a snapshot release. Let me know if it works correctly (test suite execution on github actions for wasm is somehow broken)

**Comment by StefanOltmann** [comment]
Cool, thank you, I will test it in the next days. :)

**Comment by pdvrieze** [comment]
I'll (try to) add wasi, it should merely be a matter of enabling it.

**Comment by StefanOltmann** [comment]
@pdvrieze Is it supposed to work now?

```
* What went wrong:
Execution failed for task ':compileKotlinWasmWasi'.
> Could not resolve all files for configuration ':wasmWasiCompileClasspath'.
   > Could not resolve io.github.pdvrieze.xmlutil:core:0.86.3-SNAPSHOT.
     Required by:
         project :
      > No matching variant of io.github.pdvrieze.xmlutil:core:0.86.3-SNAPSHOT:20231201.190741-12 was found. The consumer was configured to find a library for use during 'kotlin-api', preferably optimized for non-jvm, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'wasm', attribute 'org.jetbrains.kotlin.wasm.target' with value 'wasi' but:
          - Variant 'androidApiElements-published' capability io.github.pdvrieze.xmlutil:core:0.86.3-SNAPSHOT declares a library for use during compile-time:
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'wasm'
              - Other compatible attributes:
                  - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
                  - Doesn't say anything about org.jetbrains.kotlin.wasm.target (required 'wasi')
```

Reproducer: https://github.com/Ashampoo/xmpcore/tree/wasm

**Comment by pdvrieze** [comment]
This should now be available in dev/the snapshot

**Comment by StefanOltmann** [comment]
Thanks. My lib can now build using `wasmJs`() and `wasmWasi()` targets. 
I will write a small tool using them to check if it actually works.

**Comment by StefanOltmann** [comment]
@pdvrieze Looks good to me!

I build a small Compose for Web test tool to format XMP files and it works. 👍 

When you release a new stable XmlUtil version I will release a Ashampoo XMP Core with WASM/WASI support. :)

**Comment by pdvrieze** [comment]
Just released
