### ISSUE TITLE
Opt-in flag to skip content of a node with no backing fields

### ISSUE THREAD

**Issue by altavir** [pdvrieze/xmlutil#16]
There is a quite frequent case when we do not need to parse the whole XML, but only meaningful parts of it. In those cases it makes no sense to describe the whole structure in code, but only those things that are actually useful. 

The proposal is following: Make a global opt-in flag which will replace all `field not found` errors with warnings and add additional per-class annotation flag which will override global flag. It will also allow to solve #15 by automatically toggling unsafe parse for top-level node.

I can try to contribute a solution if you approve.

**Comment by pdvrieze** [comment]
I like this. One thing is that to try to add the feature to replace XmlPolyChildren annotation by SerialModule lookups I am going to have a better configuration system (that is more scaleable). You may want to wait a little for that.

**Comment by altavir** [comment]
I am in not rush. I just managed to parse my 5000 lines XML (after a little bit painful adding of definitions, I do not need) and I am happy for now.

**Comment by pdvrieze** [comment]
The new configuration contains (a not currently hooked up yet) option to specify your own code to handle
unsupported tags. If you throw an exception this will stop the parsing, otherwise the parser will ignore the problem and the function decides what to do (like creating warnings).

**Comment by altavir** [comment]
Sounds exactly what we need.

**Comment by pdvrieze** [comment]
The fixed code is now in master. There are some tests that use it. One way to trigger the new approach is:
`Xml(myModule) { autoPolymorphism = true }.stringify(value)`

You can also just have a configuration object you reuse.

Please have a look and see whether it works for you.

**Comment by pdvrieze** [comment]
The master branch now properly implements a handler hook for unexpected content. This hook can either throw an exception, print a warning, ignore it etc. This is set in the configuration block of the parser.
