### ISSUE TITLE
Error when integrated into android (java) application

### ISSUE THREAD

**Issue by AMBE1203** [pdvrieze/xmlutil#177]
This is error: Please suggest me how to fix it 
The consumer was configured to find an API of a component, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '7.3.1'. However we cannot choose between the following variants of io.github.pdvrieze.xmlutil:core:0.86.1:

**Comment by pdvrieze** [comment]
This is a duplicate of: #89 There are solutions in that issue.

**Comment by pdvrieze** [comment]
In addition, I did a few tests. It seems to work for me (both a fresh android and fresh kotlin project). What versions of gradle/kotlin are you using?
