### ISSUE TITLE
XmlUtil.xmlCollapseWhitespace() throws StringIndexOutOfBoundsException on empty attribute

### ISSUE THREAD

**Issue by armay** [pdvrieze/xmlutil#180]
Hi @pdvrieze, I faced a small bug in the latest version (0.86.2; 0.86.1 is not affected). The following line ends up with a StringIndexOutOfBoundsException if `original: String` is empty: 

https://github.com/pdvrieze/xmlutil/blob/d375df5bf1ee31f4a009946fca321b6e733c0184/core/src/commonMain/kotlin/nl/adaptivity/xmlutil/XmlUtil.kt#L49

**Comment by pdvrieze** [comment]
Just fixed it. Thanks for the report. This is indeed new code, taken from my work on xml schema support (that requires support for collapsing whitespace). In terms of serialization it is used for/needed for supporting attribute lists and attribute maps.

**Comment by armay** [comment]
Thanks a lot for the quick fix!
