### ISSUE TITLE
Using namespace

### ISSUE THREAD

**Issue by danzillo** [pdvrieze/xmlutil#193]
I would like to get the following line:
```<MyProject Version="1.0" Vendor="Me" xmlns:test="https://www.te.st/test"></MyPrject> ```
But, when I am using that data class:
```kotlin
@Serializable
@XmlSerialName(value = "MyProject")
data class SimpleXML(
    @XmlSerialName(value = "Version")
    val version: Double = 1.0,
    @XmlSerialName(value = "Vendor")
    val vendor: String = "Me",
    @XmlSerialName(prefix = "test", namespace = "https://www.te.st/test")
    val url: String = "",
```
I have recive that:
```<MyProject Version="1.0" Vendor="Me" xmlns:test="url" test:https://www.te.st/test=""></MyPrject> ```

Found only one solution:
```kotlin
@Serializable
@XmlSerialName(value = "MyProject")
data class SimpleXML(
    @XmlSerialName(value = "Version")
    val version: Double = 1.0,
    @XmlSerialName(value = "Vendor")
    val vendor: String = "Me",
    @XmlSerialName(value = "xmlns:test")
    val url: String = "https://www.te.st/test",
```
Is it right?

Maybe you can tell me what to look for in the documentation?

**Comment by pdvrieze** [comment]
There is some sort of bug in the outputs (I guess the default name code is broken) but the intended way to achieve your outcomes is to use the `@XmlNamespaceDeclSpec` annotation and it will generate namespace declarations to your heart's content (it is a single text value, declarations are separated by `;`, and are either just namespace urls or `prefix=namespace` pairs.

**Comment by danzillo** [comment]
thanks for the answer:3
