### ISSUE TITLE
Cannot deserialize node with mixed context 

### ISSUE THREAD

**Issue by underlow** [pdvrieze/xmlutil#21]
Xml node with mixed content throws exception when content in particular order:
suppose we have classes:
```
@Serializable
data class Tree(val node1: Node1)

@Serializable
@SerialName("node1")
data class Node1(
    @XmlValue(true) val text: String = "",
    val subnode1: Subnode1
)

@Serializable
@SerialName("subnode1")
data class Subnode1(@XmlValue(true) val text: String)

```

this xml can be deserialized:
```
<tree>
   <node1>
       <subnode1> text1 </subnode1>
           some text here
   </node1>
</tree>
``` 

but if we swap subnode1 and some text:

```
<tree>
   <node1>
        some text here
       <subnode1> text1 </subnode1>
   </node1>
</tree>
```  
exception is thrown:
`Exception in thread "main" nl.adaptivity.xmlutil.XmlException: Found unexpected child tag`
 
gist: [here](https://gist.github.com/underlow/4d6d5dc41674dcce44fbfd670b779d8b)

**Comment by pdvrieze** [comment]
That is a very interesting one. It should at least be consistent in handling both cases the same. Looking at your code I see the data structure. The intended use for `@XmlValue` is that it is the only non-attribute property. Basically handling mixed content is really tricky. For example what would be the correct way to parse:
```
<tree>
    <node1>
      Some text here
      <subnode1>text 2</subnode1>
      Other text here
    </node1>
</tree>
```
Beyond the "don't do that" I will have a look at how to handle this. At the very least I'll try to fix the error message so that it happens always and is clearer in explaining that `@XmlValue` and subnodes don't combine. I may add another annotation `@XmlMixed` that would apply to a list of Any and would return be assigned the full content.

**Comment by underlow** [comment]
I think it should be consistent and since it's well formed xml shouldn't fail. 
Not sure how to handle in in general but in my case I need an output like listOf(String, Subnode1, String)

**Comment by pdvrieze** [comment]
@underlow It is important to reflect that this is a serialization format (for use in a serialization framework), not a parser. I can do the mixed list and I'll see about fixing the errors (and failing consistently). I may update the handling of `XmlValue` to distinguish between collections and single values. That may be better as the current interpretation only works on "primitives" whereas tag soup handling requires a collection.

**Comment by pdvrieze** [comment]
Master should have the updated error handling plus support for lists of values being annotated as `@XmlValue`. You will need to define the correct serial module (including mapping to String).

**Comment by pdvrieze** [comment]
Just released 0.14.0.0

**Comment by underlow** [comment]
can you please provide an example if possible?

**Comment by pdvrieze** [comment]
The easiest example is in the test suite: https://github.com/pdvrieze/xmlutil/blob/9c67201298c61c209e818c5b3eca0eb5b5ecb3fc/serialization/src/commonTest/kotlin/nl/adaptivity/xml/serialization/testClasses.kt#L140-L150
Note that it requires all other properties to be attributes. You will also have to create a serial module. From a safety perspective it is advisable to add the string case to the module.

If you do not use `Any` as the base class string content may create issues with the string content still being added to the list. I have not put in any code that handles ignorable whitespace when we can't handle it.
