### ISSUE TITLE
ArrayOutOfBounds exception on deserialization

### ISSUE THREAD

**Issue by altavir** [pdvrieze/xmlutil#22]
Getting
```
java.lang.ArrayIndexOutOfBoundsException
	at nl.adaptivity.xmlutil.serialization.XmlDecoderBase$TagDecoder.decodeSerializableElement(XMLDecoder.kt:535)
	at nl.adaptivity.xmlutil.serialization.XmlDecoderBase$PolymorphicDecoder.decodeSerializableElement(XMLDecoder.kt:1054)
	at kotlinx.serialization.internal.AbstractPolymorphicSerializer.deserialize(AbstractPolymorphicSerializer.kt:59)
	at nl.adaptivity.xmlutil.serialization.XmlDecoderBase$TagDecoder.decodeNullableSerializableElement(XMLDecoder.kt:568)
	at scientifik.gdml.GDMLVolume$$serializer.deserialize(GDMLNode.kt)
```

on read from complicated input. Specifically [this test](https://github.com/mipt-npm/gdml.kt/blob/a8296c66747217dc06d366680ff522c0c5ee6b85/src/jvmTest/kotlin/sicentifik/gdml/BMNTest.kt#L37).

**Comment by altavir** [comment]
Problem could be localized to [this property](https://github.com/mipt-npm/gdml.kt/blob/a8296c66747217dc06d366680ff522c0c5ee6b85/src/commonMain/kotlin/scientifik/gdml/GDMLNode.kt#L129-L131). If I comment it, everything works.

**Comment by pdvrieze** [comment]
I'm having a look at it now. Btw. as it is a sealed class omitting the annotation should work correctly (I'm not sure about nested sealed classes - that may not work correctly yet).

**Comment by altavir** [comment]
I did not change the code yet, but got the error reported above and bizarre JS runtime error:
```
Cannot read property 'descriptor' of undefined
  ...
  at XmlDecoderBase$XmlDecoder.decodeSerializableValue_w63s0f$ (XMLDecoder.kt?5ffb:138)
```

I do not think they are related, but I need to figure it out, or I will have to roll back to the previous version.

**Comment by pdvrieze** [comment]
Javascript is nasty, but it looks like the javascript equivalent of an NPE. Btw. I've managed to create a simple test case for the original bug. It uses the "wrong" descriptor somehow. I should be able to fix it today.

**Comment by altavir** [comment]
Super. I am back to my 3d visualization and I want to release the next version with upgraded libraries.

**Comment by pdvrieze** [comment]
I've just pushed 0.14.0.1 that should fix it. I've tested it against your project and the current test works.

**Comment by altavir** [comment]
@pdvrieze I just checked and the second problem with JS I've mentioned above is resolved as well. They were related after all.
