### ISSUE TITLE
Contextual with Element throws Inline classes can not be decoded directly

### ISSUE THREAD

**Issue by hfhbd** [pdvrieze/xmlutil#220]
This did work with 0.86.3:
```kotlin
@Serializable
data class Box(
  @Contextual
  @XmlElement val i: Instant
)

@Test
fun a() {
  val box: Box = XML.defaultInstance.decodeFromString(
  """<?xml version="1.0" encoding="UTF-8"?>
     <Box>
       <i>2023-11-02T15:56:49.364+01:00</i>
     </Box>
  """.trimIndent()
  )
}
```

With 0.90.1:
```
In: Box/i Error: 3:21 - Inline classes can not be decoded directly
nl.adaptivity.xmlutil.XmlException: In: Box/i Error: 3:21 - Inline classes can not be decoded directly
	at nl.adaptivity.xmlutil.serialization.XmlDecoderBase$TagDecoderBase.decodeSerializableElement(XMLDecoder.kt:856)
	at SerializationTest$Box$$serializer.deserialize(SerializationTest.kt:14)
```

**Comment by pdvrieze** [comment]
Contextual has only (very recently) been made to (mostly) work. To diagnose this I need to know the serializer for `i`. But just from the error message it appears that the serializer attemps to decode an inline class without calling beginStructure. So I suspect you have an incorrect custom serializer.

**Comment by hfhbd** [comment]
I don't setup any custom serializer, i is kotlinx.datetime.Instant, version 0.6.0.

**Comment by pdvrieze** [comment]
@hfhbd I notice that `kotlinx.datetime.Instant` is serializable. This means you shouldn't have/need a `Contextual` annotation (if you do, it must be registered in the `SerializersModule`). The error is however not indicative of that issue.

**Comment by hfhbd** [comment]
Is this expected? I didn't need to register it in SerializerModule with 0.86.3 and I also don't need it with the Json format.

**Comment by pdvrieze** [comment]
@hfhbd I'll have a look, but the whole point of marking it `Contextual` is that it would be resolved at runtime. 0.86.3 didn't support contextual at all. I suspect that the default implementation falls back to the type-specific serializer, and somehow xmlutil doesn't.

**Comment by hfhbd** [comment]
Thanks!
Yes, you can mark an attribute as `@Contextual` to resolve a serializer as runtime, but according to the documentation you don't need to register a serializer for `@Serializable` types.
```
If type of the property marked with `@Contextual` is `@Serializable` by itself, the plugin-generated serializer is
 * used as a fallback if no serializers associated with a given type is registered in the module.
 * The fallback serializer is determined by the static type of the property, not by its actual type.
 ```

**Comment by pdvrieze** [comment]
I've fixed it. I forgot to handle contextual in the decoding case (it needs to determine the actual descriptor, rather than the "fake" one for the contextual serializer). I guess that it worked in 0.86.3 is more by accident than intent.

**Comment by hfhbd** [comment]
@pdvrieze Thank you for the fast implementation! Do you publish snapshots? If so, I will try it.

**Comment by pdvrieze** [comment]
Yes, there should be a snapshot that works.

**Comment by hfhbd** [comment]
Thanks, the snapshot (0.90.2-SNAPSHOT) does work :)
