### ISSUE TITLE
JUnit tests cannot use PullParser (0.90.2-beta1)

### ISSUE THREAD

**Issue by westnordost** [pdvrieze/xmlutil#232]
When I try to execute Java unit tests after upgrading the `io.github.pdvrieze.xmlutil:core-android` dependency to 0.90.2-beta1, tests that try to use the parser fail with the following stack trace:

```
java.lang.NullPointerException: Cannot invoke "org.xmlpull.v1.XmlPullParserFactory.setNamespaceAware(boolean)" because "$this$_init__u24lambda_u240" is null
	at nl.adaptivity.xmlutil.core.AndroidXmlReader.<init>(AndroidXmlReader.kt:36)
	at nl.adaptivity.xmlutil.core.AndroidXmlReader.<init>(AndroidXmlReader.kt:38)
	at nl.adaptivity.xmlutil.core.AndroidStreamingFactory.newReader(AndroidStreamingFactory.kt:64)
	at nl.adaptivity.xmlutil.XmlStreamingFactory.newReader(_XmlStreamingFactory.kt:103)
	at nl.adaptivity.xmlutil.XmlStreaming.newReader(XmlStreaming.jvm.kt:184)
```

Now, I see the error: I am using the `core-android` dependency but the tests run on Java (no Android). However, for some reason, this worked before (in 0.90.1), no idea why.

**Comment by pdvrieze** [comment]
I think I know what is going on. It appears that somehow your `XmlPullParserFactory.newInstance()` function doesn't return a value. You are probably doing this as an android test and `XmlPullParserFactory` is provided as a stub (returning null). You can work around it in two ways:

- Add kxml2 as dependency for the test (to get the implementation from the original library)
- Don't use the Android specific module - this will fall back to the generic implementation which is probably even a bit faster.

**Comment by westnordost** [comment]
> which is probably even a bit faster.

Faster sounds good! I have been confused by the name "generic implementation" and subsequently the name in the API (newGeneric...). It uses the pure Kotlin, i.e. multiplatform implementation for the XML parsing, right? I do wonder, if this implementation exists, is well-tested and is somewhat optimized, is there a reason left at all to use per-platform specific XML parser implementations under the hood? It sounds like extra-work to maintain that at an unknown advantage.

**Comment by pdvrieze** [comment]
I would say that the generic implementation is properly stable and better in most cases (hence it now being the default for serialization if the android/jvm modules are not explicitly included). It is the only implementation for native. As to the existing implementations, the maintenance of the wrappers is fairly light (compared to the rest of the library), and the compatibility can be useful for interoperability. This might be even more important for JavaScript (DOM).
