### ISSUE TITLE
Consider changing indent to a String?

### ISSUE THREAD

**Issue by JakeWharton** [pdvrieze/xmlutil#24]
I'm parsing XML which uses tabs for indent and I would like serialization of my models to XML to produce the same tab-indented output. Using a string for indent is a simple way to support both tabs and spaces without having to create individual options for both.

**Comment by pdvrieze** [comment]
I'll have a look at it (on first sight of the title I was wondering why you'd want it - the description is clear). This will likely be for the 1.3.70 compatible version. It'll only work for those cases where the library generates the indent (and not the delegated xml library - although you can configure that).

**Comment by pdvrieze** [comment]
This should now be in master. I've added an "indentString" property and changed "indent" to delegate to that (it assumes tabs are 8 chars, everything else 1). IndentString doesn't validate for valid whitespace at this point so if you mess up your xml it's your own fault.

**Comment by JakeWharton** [comment]
Thank you!

> IndentString doesn't validate for valid whitespace at this point so if you mess up your xml it's your own fault.

Yep, seems fair.

**Comment by pdvrieze** [comment]
I've just pushed the preliminary compatibility updates with 1.3.70/0.20, but I didn't clean up all deprecations yet. Of course 0.20 has not been released yet either. If you really need it, I could do a release with just the indent code.

**Comment by pdvrieze** [comment]
I've released 0.14.0.3 to contain this fix as well as some other fixes - compatible with 1.3.60
I've also release 0.20.0.0, but you will have to provide your own XmlWriter (rather than have the serialization format do this for you) - this code is in master, just not in the release.

**Comment by szsoftware** [comment]
@pdvrieze  do you have a short sample code fragment?
I recently opened an issue about indentString.
