### ISSUE TITLE
0.90.2 breaks XmlSerialName

### ISSUE THREAD

**Issue by sproctor** [pdvrieze/xmlutil#249]
My unit tests fail when updating to 0.90.2. It stops respecting the name given in `XmlSerialName` and instead looks for the property name. Works as expected on 0.90.1.

https://github.com/sproctor/ONVIF-Camera-Kotlin

**Comment by pdvrieze** [comment]
I've found the issue (a plain bug). It is a bit more complex here (annotating it on the attribute should not make a difference). It is an error in the `QNameMap` type. I'll release 0.90.3 soon that should have this fixed.

**Comment by sproctor** [comment]
Thanks!
