### ISSUE TITLE
[UnknownXmlFieldException] How to ignore unspecified fields when deserializing?

### ISSUE THREAD

**Issue by Rashxz** [pdvrieze/xmlutil#257]
Hi, Im tryng to deserialze a xml response that have a lot of fields, but I will only be using a few, so dont what to specify all of them as that will be time consuming and having only necesary fields will make it easier to read.

This is my class:

```
@Serializable
@XmlSerialName("Z_WEBCOM_CONSULTAResponse", "urn:sap-com:document:sap:rfc:functions", "n0")
data class SearchOrdersDTO(
    @XmlSerialName("CLIENTES", "", "")
    @XmlElement(true)
    val clients: ClientsSection,

    @XmlSerialName("TVBAK", "", "")
    @XmlElement(true)
    val tvBak: TvBakSection,
){
    @Serializable
    data class ClientsSection(
        @XmlSerialName("item", "", "")
        @XmlElement(true)
        val items: List<ClientDataItem>
    ){
        @Serializable
        data class ClientDataItem(
            @XmlSerialName("KUNNR", "", "")
            @XmlElement(true)
            val clientCode: String,

            @XmlSerialName("NAME1", "", "")
            @XmlElement(true)
            val name: String,
        )
    }
}
```

If i put all of the fields of ClientDataItem the deserialization works just fine, but if I only leave a fews I got the UnknownXmlFieldException exception. So is there anyway to just ignore the rest of fields when deserializing?

**Comment by pdvrieze** [comment]
An alternate approach is to use the fallback options (`@XmlOtherAttributes` with either `Map<QName,String>` or `Map<String,String>` - the string is default, but it should work for anything that can parse from a string), and for elements an `@XmlValue` `List<Node>` or `List<Element>` (or other type with a serializer implementing `XmlDeserializationStrategy` (this needed to consume the random xml)).

**Comment by Rashxz** [comment]
Thanks, the policy works perfectly.
