### ISSUE TITLE
Depencency not available

### ISSUE THREAD

**Issue by okalman** [pdvrieze/xmlutil#26]
Hello I'm triyng to add your serialization library to my android project but I always get 
ERROR: Failed to resolve: net.devrieze:xmlutil-serialization-android:0.20.0.0

**Comment by pdvrieze** [comment]
There is some really annoying issue with the way jcenter works with multiplatform projects. I'll try to look into it, but for now it is necessary to add "https://dl.bintray.com/pdvrieze/maven" as a remote maven repository. I'm sorry about that.
Please let me know if this does not fix the issue.

**Comment by okalman** [comment]
Hello, thank you, this seems to be working. 
If I may give you advice with a multi-module project on JCenter: deploy each module as a standalone artefact (As we do it with our MVVM Android framework https://bintray.com/thefuntastyops/mvvm-android ). It's not pretty, but it works.

**Comment by pdvrieze** [comment]
I'll try to do that. I may need to get the bintray people to help and redo the entire export because there are conflicts.

**Comment by szsoftware** [comment]
Probably same issue:
```
//implementation("net.devrieze:xmlutil-serialization:$xmlutilVersion")
  implementation("net.devrieze:xmlutil-serialization-jvm:$xmlutilVersion")
```
The commented entry does'nt resolve.
But it works without it. Btw., I'm in a gradle plugin project.

**Comment by pdvrieze** [comment]
I've been thinking on the best way to resolve it. It doesn't seem easy. For now please add:
```groovy
repositories {
	maven {
		url  "https://dl.bintray.com/pdvrieze/maven"
	}
}
```
to your gradle file. My preferred approach would be to have the platform as a maven variant (like javadoc or src) all in the same overall folder. It doesn't seem possible with the default kotlin gradle plugin. At least I haven't figured out how to hack it to do so -- it probably involves replacing some of the standard publishing infrastructure. Any suggestions are more than welcome.

**Comment by altavir** [comment]
The artifacts other than jvm sadly are not available on jcenter: https://jcenter.bintray.com/net/devrieze/.

**Comment by pdvrieze** [comment]
The problem has to do with the fact that it the project consists of 3 subprojects each with multiple directories for the same platforms. Given bintray policy there is only one link possible per project. I may need to rename move the projects to different base names so that it works, or I'd have to put everything in the same project for bintray.

**Comment by pdvrieze** [comment]
The project is now available on maven central. All modules are provided properly. Note that the coordinates have been modified (not the actual package names).
