### ISSUE TITLE
XmlConfig's omitXmlDecl = false seems to have no effect of the output

### ISSUE THREAD

**Issue by szsoftware** [pdvrieze/xmlutil#27]
`@Test fun "can serialize with xml-declaration"() {

        val expectedXml = """
            <?xml version="1.0" encoding="UTF-8"?>
            <prefix:model xmlns:prefix="namespace" version="0.0.1" anAttribute="attrValue">
                <prefix:anElement>elementValue</prefix:anElement>
                <prefix:aBlankElement></prefix:aBlankElement>
            </prefix:model>"""

        val model = MyExampleSerializableModel()

        val format = XML {
                omitXmlDecl = false
                indent = 4
        }

        val serializedModel = format.stringify(MyExampleSerializableModel.serializer(), model)

        assertEquals(expectedXml.trimIndent(), serializedModel)
    }`

Hey Paul. First thank you for your great work!

Could you give me advice how to solve the issue?

**Comment by pdvrieze** [comment]
I will have a look later. If it is on the jvm you may want to use a different xml library. The standard one has some issues. I tend to use woodstox

**Comment by pdvrieze** [comment]
I found a bug on the Android platform (and JS never supported it anyway). Android is fixed now. There is even more configuration for it. JS now supports it when using the writer that writes to strings (DOM objects don't have the declaration, only the information from it). This means that in serialization it now works on all 3 platforms. This is in commit 52bcac6.

**Comment by pdvrieze** [comment]
It is now released in 0.20.0.1
