### ISSUE TITLE
Implementation instructions in README.md: library version

### ISSUE THREAD

**Issue by szsoftware** [pdvrieze/xmlutil#29]
Hi Paul,
is there a reason why it's still mentioned implementation("...:0.13.0.1") ?

I find it cool to have latest versions reflected in quick sample and instructions samples.
I must admit, it's just a cosmetic thing. Thus if you have another opinion or find it too silly, nevermind and set the "issue" to wontfix :-D

**Comment by pdvrieze** [comment]
Now updated. Completely forgot that the version was in that document (no it's not automatically updated). I've also updated the configuration parameters in the document.
