### ISSUE TITLE
LGPL usage

### ISSUE THREAD

**Issue by r4zzz4k** [pdvrieze/xmlutil#3]
Hello, @pdvrieze! First of all, than you very much for all your contributions to Kotlin community, you are making a big change and this is highly appreciated!

Could you please clarify whether LGPL v3 is selected intentionally or you might review picked license. To my knowledge, there were no precedents yet as to whether using LGPL dependency forces JVM-based application to become LGPL-licensed or not. Though FSF has [an article](https://www.gnu.org/licenses/lgpl-java.en.html) sharing the intent that LGPL should work for Java in the same way as it does for languages compiling to shared objects, this still only describes intention, which, as you are probably aware of, can mean nearly nothing in court trials. This fact could hinder adoption of the library even for open source projects having under more permissive license, e.g. Apache 2.0 or MIT.

In any case, keep up the great work!

Regards,
Andrew.

**Comment by pdvrieze** [comment]
Good one. I'll think about it. If I change that would be to the license of the jetbrains serialisation library.

**Comment by r4zzz4k** [comment]
Great to see that you are open to this change! Having the same license as kotlinx-serialization makes sense. This would be great addition to Kotlin multi-platform toolbox! 😊

**Comment by pdvrieze** [comment]
I have just pushed the relicensed version. I've not made an actual release as it doesn't change the actual code as such.

**Comment by r4zzz4k** [comment]
Thank you very much for understanding!
README still mentions LGPL badge, you've probably missed it unintentionally.

**Comment by pdvrieze** [comment]
I will fix the readme as well
