### ISSUE TITLE
Type-restricted mixed value container with primitives

### ISSUE THREAD

**Issue by jpd236** [pdvrieze/xmlutil#30]
(I'm relatively new to Kotlin serialization, so apologies if any of this is missing something simple)

I'm trying to parse/write XML where the value of a tag is essentially a mixed subset of HTML. For example:

```xml
<tag>some text <b>some bold text<i>some bold italic text</i></b></tag>
```

I have this working similarly to the `MixedValueContainer` example from the unit tests with data classes for tag, b, and i all containing `List<@Polymorphic Any>` children and a SerializersModule to support serialization.

The main drawback here is the lack of compile-time type safety around what can go in these lists. What I'd like to do is ensure that the lists only contain b, i, or String elements. AFAIK, this can't be done with String directly because you can't declare something like an interface or sealed class that String implements.

One somewhat promising approach was to define a wrapper class for a String with a custom serializer that just serializes/deserializes the underlying string, and then define a sealed class with this wrapper class as well as the other tags. This introduces full type safety and works when serializing an object; however, deserialization seems to fail because it doesn't know what to do with the vanilla string in the XML.

Is it feasible to define a mixed value container with only some restricted subset of valid child types at compile time which works for both serializing and deserializing?

**Comment by pdvrieze** [comment]
The code I just pushed has an initial start (in test code) to allow this to work. It is more complex than it looks, but I'll treat this as a feature.

**Comment by pdvrieze** [comment]
The behaviour you want is somewhat complex, but you can see in https://github.com/pdvrieze/xmlutil/blob/master/serialization/src/commonTest/kotlin/nl/adaptivity/xml/serialization/TestMixedTypesafe.kt how this can be done
