### ISSUE TITLE
Provide Jackson compatibility

### ISSUE THREAD

**Issue by nkiesel** [pdvrieze/xmlutil#33]
Hi,
I'm currently investigating if we can abandon Jackson in favor of Kotlin serialization.  We use XML, JSON, and YAML.  For XML I was looking at this adapter.  However, the generated XML is different from Jackson (w/o "wrapper") configuration:
```
jackson: <Team><members><name>Joe</name><age>15</age></members></Team>
kotlin: <Team><Person name="Joe" age="15"/></Team>
```
This was generated using
```kotlin
@Serializable data class Person(val name: String, val age: Int)
@Serializable data class Team(val members: List<Person>, val colors: List<String> = listOf())

fun main() {
    val t = Team(listOf(Person("Joe", 15)))

    val mapper = XmlMapper.builder().defaultUseWrapper(false).build().registerKotlinModule()
    println("jackson: ${mapper.writeValueAsString(t)}")

    val xml = XML()
    println("kotlin: ${xml.stringify(Team.serializer(), t)}")
}
```
If I add annotations
```kotlin
@Serializable data class Person(@XmlElement(true) val name: String, @XmlElement(true) val age: Int)
@Serializable data class Team(@XmlChildrenName("members", "", "") val members: List<Person>, val colors: List<String> = listOf())
```
I get
```
kotlin: <Team><members><members><name>Joe</name><age>15</age></members></members></Team>
```
which is closer (besides the double "members").  But I really would like to avoid doing this to all the data classes.  Could we have a `val xml = XML(jackson = true, wrapper = false)` which does this all automatically?

**Comment by nkiesel** [comment]
I just learned that using
```
@Serializable data class Team(@XmlSerialName("members", "", "") val members: List<Person>, val colors: List<String> = listOf())
```
will produce the same output as Jackson. Thus, this is solved (with downside that I would have to repeat them parameter name).  I still wold like to get all of this w/o adding all the annotations.

**Comment by pdvrieze** [comment]
The library was designed to provide a "natural" XML experience. In line with XML schema it is the type that provides the tag name, not the property of the tag. However, these are fundamentally choices. I would be open for pull requests that would make this behaviour configurable.

**Comment by pdvrieze** [comment]
I've just released a version that uses a "policy" object to configure serialization. You may want to have a look at that. It would allow you to have a custom policy rather than using the annotations. Let me know if that works for you. I'll see at adding some more documentation for it as well. I may add a jackson compatibility policy to make it easier for people in your case. Btw. how does Jackson handle polymorphic values/lists?

**Comment by pdvrieze** [comment]
I've added an example and documentation on how to use the policy to do this. Have a look: https://github.com/pdvrieze/xmlutil/blob/master/examples/JACKSON.md

It should solve your problem. I don't want to put this in the library proper as it isn't quite complete and may need a different approach for different cases.

**Comment by nkiesel** [comment]
Yes, that looks like a good approach. Thank you!
