### ISSUE TITLE
get a map of all attributes

### ISSUE THREAD

**Issue by chumpa** [pdvrieze/xmlutil#34]
How can I get mapOf attribute names and values? 
Sample xml would be:

<a b="c" d="e" f="g" .../>

Every attribute is unique so mapOf<String,String> is very good for me.

I'm using 0.20.0.0 version and thank you so much for your work.

**Comment by chumpa** [comment]
I found unknownChildHandler, that's great. Is it possible to use it only on high-level but on nested ones with different implementations as well?

**Comment by pdvrieze** [comment]
First of all, the library isn't really designed for this (it is designed for a predictable list of names - this is reinforced by the design or serialDescriptor). But, there is a way to do this. The library is intentionally designed to give you access to the underlying XML parser/serializer. Have a look at `nl.adaptivity.xmlutil.serialization.CompactFragmentSerializer` . Basically you create a custom serializer/deserializer. In this class you check that you have been given an XmlInput or XmlOutput. If not, you handle things as regular content. If yes, you get access to the underlying xml parser or serializer and read/write the tags directly.

At the same time it may be an option to actually allow this to be an option to map serialization. I'll keep this on as a future feature.

**Comment by pdvrieze** [comment]
The current version has an annotation that supports this using `@XmlOtherAttrs` with a Map<QName,String> or Map<String, String>. Note that it only picks up unknown attributes.
