### ISSUE TITLE
Is it possible to detect CDATA usage?

### ISSUE THREAD

**Issue by glureau-betclic** [pdvrieze/xmlutil#38]
I'd be able to distinguish if the content of a XML tag uses CDATA or not, and potentially if it uses '<' or '&lt;'.

With my current setup, the text I get from these 2 exemples is the same result.

```
@Serializable
data class Foo(
    @XmlValue(value = true) val text: String = ""
)
```

```
<foo>1 &lt; 2</foo>
<foo><![CDATA[1 < 2]]</foo>
```

**Comment by pdvrieze** [comment]
I'm not sure why you want to do this, but the serialization part of the library does not make a distinction between text and cdata. It can't really. I don't think it will use cdata at all to output data, but theoretically it could be written that this is configurable. From an XML perspective both are more or less equivalent. What you can do is to have a custom serializer where you check whether you are using an xmldecoder and get the underlying xml source.

**Comment by pdvrieze** [comment]
One thing to add, in the new version the `XmlReader` will actually be a `BufferedXmlReader`, meaning that it supports peeking values without "moving the parser on". This may make it easier to detect this difference.

**Comment by glureau-betclic** [comment]
My use case, I'm trying to check that a XML file generated by a third party respect a list of rules. So I want to be sure it uses CDATA and '<' or if it uses '\&lt;' (both combination are ok, but indeed using '<' without CDATA breaks the XML format).

**Comment by pdvrieze** [comment]
If you want this, don't use the serialization library. Just use the XML parser directly. The core module provides just this wrapper. That allows you to parse fully.
An option that may work in your case would be to create a filtering/delegating reader. Basically this is an XmlReader that will actually just forward to another XmlReader, but in your case you'll want to do your checks. Be aware though that at that point you will already have parsed xml. In other words, the default entities (and unicode character sequences) will already be replaced at this point.
As the library is not actually an XML parser, rather it delegates to already existing parsers it is limited in what it can do. The underlying parsers can be validating, but are not required to be (on the Jvm you get the parser that the service loading mechanism will give you - the reason that the test configuration pulls in woodstox as the jvm default one is broken in too many ways).
