### ISSUE TITLE
Serialization 1.0

### ISSUE THREAD

**Issue by altavir** [pdvrieze/xmlutil#39]
Kotlin 1.4 and serialization 1.0.

@pdvrieze I know that you work on it, but I put it here for tracking. Please do not forget to enable IR mode for JS.

**Comment by pdvrieze** [comment]
Can you have a look at the dev branch. I have just pushed it. I'll probably release it as prerelease tomorrow. I'm planning to look at stabilising this library as well, but it needs some further work, including api (hiding stuff), jigsaw, dokka. Especially the core library needs work in that sense, the serialization part is now quite well-baked although it has to use some internal api's.

**Comment by jershell** [comment]
Currently, if I use xmlutil and kotlin.serialization:1.0.0-RC together on one project I have the error ```Overload resolution ambiguity```

**Comment by pdvrieze** [comment]
@jershell I've just released 0.80.0-RC. The 0.20.0.10 version is still only targeting 0.20. It is as close as it can be, but kotlinx.serialization 0.20 and 1.0 are not compatible at all. There are significant API changes so a new release was needed anyway. Please provide any feedback on the new approach..

**Comment by jpd236** [comment]
0.80.0-RC seems to be working for my project - [here's my migration commit](https://github.com/jpd236/kotwords/commit/14a8312b6a5516e5d1ddde519efbbf9773c6db5e) in case it helps anyone else migrating.

**Comment by jershell** [comment]
@pdvrieze The release resolved the trouble with ```Overload resolution ambiguity```! Thx!

**Comment by pdvrieze** [comment]
I've just released the 0.80.0 version. It even has new configurable behaviour for defaults (using the standard default infrastructure, although the configuration of the policy defaults to the old behaviour with the @XmlDefault annotation).
