### ISSUE TITLE
Support for Ktor to use XmlUtil for server and clients

### ISSUE THREAD

**Issue by fkrauthan** [pdvrieze/xmlutil#40]
I am currently trying to consume a XML API with a ktor-client but struggle a bit with how I can embed the framework as part of a Feature that will auto serialize my input body to XML and automatic de-serialize the returned XML data to an object (similar to how I can use JSON at the moment: https://ktor.io/clients/http-client/features/json-feature.html)

**Comment by pdvrieze** [comment]
I've had a quick look. What you would need to do is to make an `XmlFeature` analogous to `JsonFeature`, You may still also have to update `KotlinxSerializer` (or create your own variant) to accept XML. Btw. as this library only wraps an XML implementation it doesn't support native/iOs as I haven't gotten to do so.

**Comment by fkrauthan** [comment]
I found a small workaround somewhere online (forget where) and updated it a bit to support generics. But maybe it helps other people for the time beeing:

```
class XMLSerializer(private val format: XML = XML()) : JsonSerializer {

    override fun read(type: TypeInfo, body: Input): Any {
        val text = body.readText()
        val deserializationStrategy = format.serializersModule.getContextual(type.type)

        val mapper = deserializationStrategy
            ?: type.kotlinType?.let { serializer(it) }
            ?: type.type.serializer()

        return format.decodeFromString(mapper, text) ?: error("Failed to parse response of type $type. The result is null.")
    }

    override fun write(data: Any, contentType: ContentType): OutgoingContent {

        val serializer = if (data is GenericData) {
            data.serializer
        } else {
            data::class.serializer() as KSerializer<Any>
        }
        val payload = if (data is GenericData) {
            data.data
        } else {
            data
        }
        val text = format.encodeToString(serializer, payload)
        return TextContent(text, contentType)
    }

}

data class GenericData(
    val data: Any,
    val serializer: KSerializer<Any>,
)
```

And you use it like this:
```
        HttpClient(CIO) {
            install(JsonFeature) {
                serializer = XMLSerializer(XML())
                accept(ContentType.Application.Xml, ContentType.Text.Xml)
            }
        }
```

**Comment by pdvrieze** [comment]
I've just released a ktor module that provides this support explicitly. It is mostly similar to the json implementation (but doesn't reuse the streamconverter as xml serialization supports direct reading from and writing to streams rather than using string intermediates).

**Comment by wguttmn** [comment]
Does the ktor module support both server and client ?

**Comment by pdvrieze** [comment]
The design of this module is based upon ktor-serialization. It supports both reading and writing of data (encoding and decoding), and should be analogous to using the support (both should be able to work together with content negotiation too). The main difference (except for the different format) is that the xml module does not use an intermediate string, but directly serializes to/deserializes from streams (it will need to parse the entire input though as serialization does not support streaming (yet)).

**Comment by rgbrizzlehizzle** [comment]
looked through the example code and it seems to only cover ktor server `ContentNegotiation`, perhaps this should be reopened or list ktor client support as a separate ticket?

**Comment by rgbrizzlehizzle** [comment]
Going to be going a different route with a project I'm working on, but I pretty much wrapped up an Xml plugin for ktor client and put it into a github gist here https://gist.github.com/rgbrizzlehizzle/d0695e23386024dfa84f3df6129c937a 

if anyone wants to take over and port the code into either this library or ktor itself feel free 😃 

Takes heavy inspiration from the `JsonFeature` plugin that is part of the ktor client library
