### ISSUE TITLE
 anyone can help

### ISSUE THREAD

**Issue by heyleon** [pdvrieze/xmlutil#42]
```
 <?xml version="1.0" ?>
<S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/">
    <S:Body>
        <ns2:Ge xmlns:ns2="http://www.gxtlink.com/webservice/">
            <result>
                <code>0</code>
                <data>
                    <project>get</project>
                    <unit>p</unit>
                </data>
            </result>
        </ns2:Ge >
    </S:Body>
</S:Envelope>
```

how can I parse this xml ?
I tried to parse it but failed

**Comment by pdvrieze** [comment]
Assuming that you want to use the serialization library you would need to make sure that the content of the body is polymorphic. You also need to use XmlSerialName annotations to register the namespaces. If you have some classes that you tried, I may be able to see where you go wrong.

**Comment by ciscorucinski** [comment]
Seems like a documentation issue. With Kotlin 1.4 being released with kotlinx.serialization 1.0, more people will be seeing this library. I would hope that you can prioritize getting samples up and running rather than pointing to test classes with minimalized XML that is hard to read and comprehend

**Comment by pdvrieze** [comment]
I'll see what I can do, but this is not my day job at all (it is a side-effect of a research prototype). Any contributions are welcome.

**Comment by ciscorucinski** [comment]
Fully understood

**Comment by pdvrieze** [comment]
I've added an example [submodule](../tree/master/examples). There is something disfunctional about your xml (the content of your message is in the anonymous namespace). It can be parsed though. Find the example in [SOAP.md](../tree/master/examples/SOAP.md)

**Comment by chumpa** [comment]
Hi Paul,
latest 0.81.1 version with Kotlinx-Serialization v1.4.31 cannot build SOAP, due to new SerializationStrategy. Could you please update this sample?

**Comment by pdvrieze** [comment]
I've just had a look at the code. When I look at the latest code in the master branch, it works correctly (and compiles). The code in the markdown was slightly out of sync, but shouldn't be materially changed. Could you share the error message you get?

**Comment by chumpa** [comment]
Sorry for disturbing, it's my bad. Downloaded *kt are built well. Have a nice day!

**Comment by chumpa** [comment]
Just a note, now we can extend SOAP sample with SOAP:Header as a CompactFragment, just parsing it to handler's business. For my case it was very great because part of SOAP responses provide some dynamic content:

```xml
<S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/">
<S:Header>123456<a/></S:Header>
<S:Body>
<A xmlns="urn:vendor-com:A" a="stringA" x="1"/>
</S:Body>
</S:Envelope>
```

This code is just for example and works for me, I cannot understand details of private constructor yet:

```kotlin
@Serializable
@XmlSerialName("Envelope", "http://schemas.xmlsoap.org/soap/envelope/", "S")
data class Envelope2<BODYTYPE>(
    @XmlElement(true)
    @Contextual
    @XmlSerialName("Header", "http://schemas.xmlsoap.org/soap/envelope/", "S")
    val header: CompactFragment? = null,
    val body: Body<BODYTYPE>,
) {
    @Serializable
    @XmlSerialName("Body", "http://schemas.xmlsoap.org/soap/envelope/", "S")
    class Body<BODYTYPE>(@Polymorphic val data: BODYTYPE)
}

@Serializable
@XmlSerialName("A", "urn:vendor-com:A", "")
data class A(val a: String, val x: Int = 1)

@Serializable
@XmlSerialName("B", "urn:vendor-com:B", "")
class B(val b: String, val y: Int = 2)

private val xmlmodule = SerializersModule {
    polymorphic(Any::class) {
        subclass(A::class, serializer())
        subclass(B::class, serializer())
    }
}
private val xmlserializer = XML(xmlmodule) {
    xmlDeclMode = XmlDeclMode.None
    autoPolymorphic = true
}
```

**Comment by chumpa** [comment]
Moreover CompactFragment is required to parse SOAP:Fault which is very dynamic.

**Comment by pdvrieze** [comment]
I'll have a look at extending the example, although perhaps the headers are a bit more complex. Depending on the role of the receiver some headers are valid to ignore(not understand) and others must be processed. But of course it depends on your use case.
