### ISSUE TITLE
How to deserialize slightly different polymorphic format?

### ISSUE THREAD

**Issue by floscher** [pdvrieze/xmlutil#45]
I'm currently trying to deserialize XML-files that are formatted something like these two with version `0.80.1`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<fruit type="apple" name="MyApple" numAppleSeeds="5">
  <!-- child elements omitted for simplicity -->
</fruit>
```
```xml
<?xml version="1.0" encoding="UTF-8"?>
<fruit type="tomato" name="MyTomato" color="red">
  <!-- child elements omitted for simplicity -->
</fruit>
```

I would like to deserialize them into something like this:
```kotlin
@Serializable
@SerialName("fruit")
sealed class Fruit {
  abstract val name: String
}

@Serializable
@SerialName("apple")
data class Apple(
  override val name: String,
  val numAppleSeeds: Int
): Fruit()

@Serializable
@SerialName("tomato")
data class Tomato(
  override val name: String,
  val color: String
): Fruit()
```

This is almost what I want, but it expects the XML to look like this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<fruit type="apple">
  <value name="MyApple" numAppleSeeds="5">
    <!-- child elements omitted for simplicity -->
  </value>
</fruit>
```
```xml
<?xml version="1.0" encoding="UTF-8"?>
<fruit type="tomato">
  <value name="MyTomato" color="red">
    <!-- child elements omitted for simplicity -->
  </value>
</fruit>
```

But I need it to look more like the JSON serialized from the same class hierarchy with all attributes on the same element:
```json
{"type":"apple","name":"MyApple","numAppleSeeds":5}
```
```json
{"type":"tomato","name":"MyTomato","color":"red"}
```

What's the easiest way to achieve this? Is there some annotation to put somewhere, that puts the attributes of the `<value>` element directly on the `<fruit>` element? Or do I have to write a custom serializer?

Unfortunately I don't have control over the XML-Format, because it is generated by a third-party program.

I played around with this, but couldn't come up with a satisfactory solution so far.

Thank you in advance!

**Comment by floscher** [comment]
I think I need something like https://github.com/Kotlin/kotlinx.serialization/blob/4bd949b0634fd498f847b1e059826cc7e67adf07/formats/json/commonMain/src/kotlinx/serialization/json/JsonContentPolymorphicSerializer.kt , but for XML.

When extending that serializer you just need to implement
```kotlin
fun selectDeserializer(element: JsonElement): DeserializationStrategy<out T>
```
which can inspect the content of the JSON element and decide based on that, which deserializer to use.

**Comment by pdvrieze** [comment]
Unfortunately the format of the third party program doesn't quite work according to the way XML was designed/intended to work. I see two options to address this:
- In the case that the child content cooperates you can do the following: have a serialization-only type that contains all properties (some optional) and then have a custom serializer for fruit that gets the appropriate fruit subtype for the child content (and serializes properly as well). This depends on the types not being wildly incompatible, in particular in terms of child content. The advantage is low complexity and no need to special case XML.
- Use a filter to transform the xml on input/output. An example of how this works can be seen in https://github.com/pdvrieze/xmlutil/blob/master/examples/DYNAMIC_TAG_NAMES.md . In that case you probably want to enable automatic polymorphism (get rid of the nesting) and then on reading use the attribute to translate `<fruit type="apple" ...` into `<Apple ...`. And on writing the other way around

**Comment by floscher** [comment]
Thank you for the answer! I think I'll then go for something like your first solution, that looks easier to me. In my case there are only three possible subtypes and about half of the attributes in each type are common for all subtypes, so the overhead should be manageable, when duplicating the properties to a new class just for serializing.

I've put a simplified version of what I'm going to do in my project at: https://github.com/floscher/xmlutil/tree/polymorphic-fruit-example/examples/src/main/kotlin/net/devrieze/serialization/examples/custompolymorphic
If you'd find that useful to archive as an example, feel free to [pull the `polymorphic-fruit-example` branch](https://github.com/pdvrieze/xmlutil/compare/dev...floscher:polymorphic-fruit-example?expand=1).
