### ISSUE TITLE
How to use this library as a Retrofit Converter and use it to call SOAP web services on Android?

### ISSUE THREAD

**Issue by Rishabh-More** [pdvrieze/xmlutil#47]
I want to call SOAP web services on Android platform using Retrofit Http Client. However, I need a Converter Factory to serialize/deserialize request & response bodies to POJOs used in my project. 

For JSON there are some really good serializers, like Jackson, Gson & Moshi. But the converter factory for XML parsing they give is [SimpleXML](https://github.com/square/retrofit/tree/master/retrofit-converters/simplexml) and it's no as feature rich at all for our use cases. And the [JAXB Converter](https://github.com/square/retrofit/tree/master/retrofit-converters/jaxb) does not work on Android, so that is out of the question.

So I guess I'm left with no choice but to write my own Converter Factory. Thing is I've never really created my own Converter Factory for serialization. So this is all unknown territory for me here. So any help will be gladly appreciated.

Maybe you guys can provide a retrofit converter package for android in the near future. That would be absolutely amazing. so yeah, NEED HELP.

**Comment by pdvrieze** [comment]
It's just me (and mainly I'm an academic - this project is just a side project for my main research project). But could you give some indication as to where you are stuck. I've had a very quick look at the code for the JAXB converter and it is overall quite simple code. I would suspect that the "correct" pojo data structure (and possibly custom serializers) would perhaps be the challenge. Maybe just an example would do.

**Comment by wax911** [comment]
I would not mind taking a look at this issue, later on if I get some free time and possibly work on a PR <3 love the project btw @pdvrieze

**Comment by pdvrieze** [comment]
I think that this is best done in a separate module, so if you could do that it would be great.

**Comment by wax911** [comment]
By the way @Rishabh-More what do you mean by:
> `But the converter factory for XML parsing they give is SimpleXML and it's no as feature rich at all for our use cases. And the JAXB Converter does not work on Android, so that is out of the question.`
SimpleXML still works on android with both java and kotlin, in fact I have an application that is currently using SimpleXML and it works as expected

**Comment by wax911** [comment]
Hi @pdvrieze and @Rishabh-More, so today I realised that a retrofit converter already exists for `kotlinx.serialization` [retrofit2-kotlinx-serialization-converter](https://github.com/JakeWharton/retrofit2-kotlinx-serialization-converter) by Jake Wharton. I only figured out the connection when I saw that the `XML` class implements `kotlinx.serialization.StringFormat` .e.g:

![image](https://user-images.githubusercontent.com/7859175/105488453-4bc7f480-5cba-11eb-8408-cc83608b3dc8.png)

The usage is detailed here using with the exception of it using JSON instead, [read more](https://github.com/JakeWharton/retrofit2-kotlinx-serialization-converter#usage) and if you want to use `XML` the it can be done as follows:

![image](https://user-images.githubusercontent.com/7859175/105488733-c2fd8880-5cba-11eb-953d-64ccf57cfc6c.png)

**Comment by pdvrieze** [comment]
Looking at [https://github.com/JakeWharton/retrofit2-kotlinx-serialization-converter](retrofit2-kotlinx-serialization-converter) it requires specifying the format. As such there is no additional burden using XML rather than Json. The only additional option would be to create a version that uses the iostream support of the xml format.
