### ISSUE TITLE
decodeEnum seems to be broken

### ISSUE THREAD

**Issue by altavir** [pdvrieze/xmlutil#5]
For some reason it compares the deserialized string with class name of Enum instead of its value.

I did not found tests for enums.  I use `@XmlElement(false)` on my enum property to encode it as attribute instead of element, but it does not seem to cause the problem.

**Comment by pdvrieze** [comment]
Merged code should fix this

**Comment by sschuberth** [comment]
Could I be running into the same issue, though with `@XmlElement(true)`? I have

```
@Serializable
data class HockeyLiga(
    @XmlElement(true) val LigaBereich: String,
    @XmlElement(true) val LigaBereichNr: Int,
    val LigaRegion: LigaRegion,
    val LigaAK: LigaAltersklasse,
    @XmlElement(true) val LigaSpieljahr: Int,
    @XmlElement(true) val LigaSaison: String,
    @XmlElement(true) val LigaID: String,
    @XmlElement(true) val LigaObertitel: String,
    @XmlElement(true) val LigaTitel: String
)
```

and

```
 <HockeyLiga>
  <LigaBereich>Bund und Regional</LigaBereich>
  <LigaBereichNr>1</LigaBereichNr>
  <LigaRegion>N</LigaRegion>
  <LigaAK>D</LigaAK>
  <LigaSpieljahr>2</LigaSpieljahr>
  <LigaSaison>FELD23</LigaSaison>
  <LigaID>REG-NORD-D</LigaID>
  <LigaObertitel>Interessengemeinschaft Nord</LigaObertitel>
  <LigaTitel>Regionalliga Nord - Damen</LigaTitel>
 </HockeyLiga>
```

and deserializing gives me

```
Could not find a field for name (dev.schuberth.hockey.model.bhv.HockeyLiga) HockeyLiga/LigaAK (Element)
  candidates: LigaBereich (Element), LigaBereichNr (Element), LigaRegion (Element), LigaAltersklasse (Element), LigaSpieljahr (Element), LigaSaison (Element), LigaID (Element), LigaObertitel (Element), LigaTitel (Element) at position Line number = 89
```

So why is it listing `LigaAltersklasse (Element)` as a candidate although the field name is `LigaAK`? And interestingly, the candidate becomes `LigaAK (Element)` when using `@XmlElement(false)` on the property.

**Comment by sschuberth** [comment]
> I'm not sure why it becomes `LigaAK (Element)` as it should be `LigaAK (Attribute)`

Though `LigaAltersklasse` isn't a primitive type, and thus it can't be an attribute, or?

> unless you change something in the policy

Nope, I didn't, using plain `XML()` for now.

**Comment by pdvrieze** [comment]
> Though `LigaAltersklasse` isn't a primitive type, and thus it can't be an attribute, or?

This may be why it is still an `Element` candidate, but then the name is derived not using the effective type, but rather the expected type. I'll review and fix that. Note that enums can be treated as strings so should work as attributes.

**Comment by sschuberth** [comment]
> I'll review and fix that.

Thanks!
