### ISSUE TITLE
Compile for serialization 1.1.0-RC

### ISSUE THREAD

**Issue by altavir** [pdvrieze/xmlutil#51]
Due to https://github.com/Kotlin/kotlinx.serialization/issues/1331 libraries are not backward compatible on JS-IR. Is it possible to publish a 1.1.0-RC compatible version?

**Comment by pdvrieze** [comment]
I'm working on it. Supporting inline classes correctly is a bit more complex than desired.

**Comment by pdvrieze** [comment]
Just released as v0.81.0
