### ISSUE TITLE
Cannot serialize CDATA which contain <, >

### ISSUE THREAD

**Issue by phucynwa** [pdvrieze/xmlutil#55]
I think a library like TikXml has supported CDATA very well. Why XmlUtil isn't ?

I want to parse xml content from [https://phatgiao.org.vn/loi-phat-day.rss](https://phatgiao.org.vn/loi-phat-day.rss) however, I got an error.

I used inline class to wrap content, use annotation @XmlValue(true) but nothing works.

Hope you might support CDATA better.

Thank you.

**Comment by phucynwa** [comment]
Sorry, it's my bad. After using namespace and prefix, everything is ok.
```kotlin
    @XmlSerialName("encoded", "http://purl.org/rss/1.0/modules/content/", "content")
    @XmlElement(true)
    val contentEncoded: String,
```

**Comment by pdvrieze** [comment]
CData (even with <) should work, but the serialization library is namespace aware, so having the right namespaces matters. Note though that feeds tend to be all kinds of a mess of XML, so using a string approach such as serialization may be limited. (Much of it is conflicting standards though)
