### ISSUE TITLE
How to get localname when using XmlPolyChildren?

### ISSUE THREAD

**Issue by Lewik** [pdvrieze/xmlutil#57]

**Comment by pdvrieze** [comment]
The full algorithm on how XmlPolyChildren works starts [here](https://github.com/pdvrieze/xmlutil/blob/cc456d5ca3028af6a062f0282e8106a0bd168f19/serialization/src/commonMain/kotlin/nl/adaptivity/xmlutil/serialization/structure/XmlDescriptor.kt#L621). It contains a list/array of children. For each child it works like:

To be short:
 - If there is no assignment (`=` character):
   - take the string after the last period as localname.
   - Use the parent as prefix/namespace
   - Use the full string to specify the type (can be a partial name in which case it tries to be smart)
   - If the type has a requested name, use that name
 - If there is an assignment this introduces a name specification for the tag
   - If there is a separator (`:`) then the text before the `:` (after the `=`) is the xml prefix, the text after is the local name.

But please *note* that there is probably little need to use this annotation when using modules. (This annotation subsumes modules).
