### ISSUE TITLE
Polymorphism based on attribute value

### ISSUE THREAD

**Issue by chumpa** [pdvrieze/xmlutil#58]
I have XML to parse as following:

```
<bindings>
	<param name="vmdefault">
		<value/>
	</param>
	<param name="vmstrategy">
		<value>1</value>
	</param>
	<param name="table">
		<value>
			<properties>
				<property name="30">BUS2031</property>
				<property name="2059">BUS2032</property>
			</properties>
		</value>
	</param>
</bindings>
```
I cannot mix @XmlValue(true) and properties, because XmlValue doesn't allow child elements.
So I need some kind of polymorphism a-la SOAP, right? But I'm scared of the way of such polymorphism because it must be bind to param@name in my case.

**Comment by chumpa** [comment]
I tried to get /bindings/param as org.w3c.dom.Element and failed:

```
    val xml = XML() {
        indentString = "\t" // Set indentation
        xmlDeclMode = XmlDeclMode.None
        autoPolymorphic = true
    }

@Serializable
@XmlSerialName("bindings", "", "")
data class Bindings(
    @XmlElement(true)
    @XmlSerialName("param", "", "")
    val param: List<org.w3c.dom.Element> = listOf()
)
```

Error is: 
```
nl.adaptivity.xmlutil.serialization.UnknownXmlFieldException: Could not find a field for name param at position Line number = 2
Column number = 26
System Id = null
Public Id = null
Location Uri= null
CharacterOffset = 36
```

**Comment by chumpa** [comment]
After looking to variety of /bindings/param/value kind of serialized objects, I've faced with a lot of different cases. So I think I need to write custom deserializer. 
Could I do it only for Value class?

**Comment by chumpa** [comment]
I've found **nl.adaptivity.xmlutil.util.CompactFragment** and Fruit example. That's great! At first I will try CompactFragment.

**Comment by pdvrieze** [comment]
`CompactFragment` is a class that is there to store arbitrary xml as text. It it available as text (with namespaces recorded on best effort basis - ie prefix references in attributes are not supported). The reason I created it is to be able to embed xml into a configuration that would then be independently produced upon certain conditions (after transformation). Where the content of the xml is significant in the configuration, it is arbitrary as far as the code using the configuration is concerned.

**Comment by chumpa** [comment]
Thank you for comment. Currently I solved that using `@XmlValue(true) val value: List<@Polymorphic Any> = listOf(),`

https://github.com/rsugio/karlutka/blob/3382b7cf21c997b94fcda70a83122a7be2b8540c/src/main/kotlin/k1/Hm.kt#L113

Thank you very much, Paul.

**Comment by pdvrieze** [comment]
Indeed, that is the intended purpose of `@XmlValue` in the context of a list property. This use is by design for the "arbitrary, but understood" content case.
