### ISSUE TITLE
Could not find core-0.82.0-samplessources.jar

### ISSUE THREAD

**Issue by MolchanovDmitry** [pdvrieze/xmlutil#67]
Hello.

I want to try your library with kotlin multiplatform mobile to share code between android and ios.
When I put dependencies in build.gradle.kts androidMain.dependencies block it works fine.
But when I put dependencies in build.gradle.kts commonMain.dependencies block gradle synchronization finished with error.
My test project: https://github.com/MolchanovDmitry/KmmJsonXmlParseSample

**Steps to reproduction:**
1. Start Android studio.
2. Install KMM plugin.
3. Create project with KMM Application template.
4. Add repository.
5. Put `implementation("io.github.pdvrieze.xmlutil:core:0.82.0")` in commonMain block of build.gradle.kts

**Expected result:**
BUILD SUCCESSFUL.

**Actual result:**
```
Unable to build Kotlin project configuration
org.gradle.internal.resolve.ArtifactNotFoundException: Could not find core-0.82.0-samplessources.jar (io.github.pdvrieze.xmlutil:core:0.82.0).
```

Can you get me advice?

**Comment by pdvrieze** [comment]
I checked your project. First of all, you didn't include the gradle wrapper scripts or the gradle directory. Putting the 7.0 version of the wrapper in it, check completes.
Note that no samplesources artefact exists (or ever existed), and isn't/shouldn't be referenced. I suspect that updating your gradle version would solve the problem.

**Comment by MolchanovDmitry** [comment]
I updated gradle to 7.0, but got the same result.
If I transfering xmlutil dependencies from androidMain to commonMain gradle.kts block, Android studio doesn't show kmm resources and disables static code analizator.
But code is able to compile.
It's IDE issue. I'll write about it to JetBrains.
Thank you for your attention.

**Comment by pdvrieze** [comment]
I've found the main problem. The cause of the issue is that the library doesn't support kotlin-native (as - for now - it incorporates existing platform xml libraries rather than providing its own). I may create a platform independent version in the future (Effectively I already have it for writing XML, but not for parsing it). Have a look at https://youtrack.jetbrains.com/issue/KTIJ-10769 for more information.
