### ISSUE TITLE
Serializing some elements as CDATA?

### ISSUE THREAD

**Issue by KLBonn** [pdvrieze/xmlutil#71]
Hello,

just recently I found this library, and I really like it!

However, in order to communicate to a specific application, I have to output some classes / elements as CDATA, instead of simple text.
I know, considering XML standards, both representations of text content should be equal in value. But on our application, they are not 😞 

Is there a way to enforce CDATA output for String attributes? E.g. applying a different ElementKind with some custom policy? Or some annotation magic?

**Comment by pdvrieze** [comment]
I've added the feature to the dev branch that will allow this to be done using an annotation. In the meantime, you can use a custom serializer that normally delegates to StringSerializer, but if the encoder is an instance of `XmlOutput` it can directly write the value to the `XmlWriter` using cdsect. Then were-ever you need this, you annotate it `@Serializable(CDSectSerializer::class)`.

**Comment by KLBonn** [comment]
Thank you for your advice! Tried your suggestion "In the meantime...", and it works perfectly fine for me 👍 

If / when there is a simpler way using your new annotation, I will be happy to update my code accordingly of course.

**Comment by KLBonn** [comment]
Update: Including my prototype in another application prove difficult due to https://github.com/Kotlin/kotlinx.serialization/issues/685 . Had to keep a separate Gradle submodule for those 3 classes 😒 

If your design with a "proper" annotation will work with kapt, that would be a good reason to follow on with it.

**Comment by pdvrieze** [comment]
I've been working on another application (that uses this library). I've put in quite some fixes based on that, I should have a release reasonably soon (once I can see that it works). Of course the kapt issues are a different thing.

**Comment by pdvrieze** [comment]
Just released in 0.84.0-RC1
