### ISSUE TITLE
Unable to resolve ktor:0.84.0

### ISSUE THREAD

**Issue by cmota** [pdvrieze/xmlutil#82]
Hello Paul!

Let me start by saying that's a great lib! 

I noticed that Ktor 2.0 now uses it for deserialization and I wanted to try it on a project that I have 🙂.

If I'm not mistaken, I just need to add the `xmlutil:ktor` to my `commonMain` dependency, right?

I'm getting an error while doing this:
> `Could not resolve io.github.pdvrieze.xmlutil:ktor:0.84.0.

I've noticed that the library is both on mavenCentral and on your nexus, but in any case, it seems Gradle is unable to find it - do you have any idea what I might be doing wrong? I'm currently targeting Android and iOS on a Multiplatform project and I already cleared the cache and refresh the project dependencies.

**Comment by pdvrieze** [comment]
I am not sure, but in any case you don't need to use that coordinate. You can use the ktor coordinate for xml and it should work. This coordinate only adds streaming support (under the hood) so it is probably not worth it.
