### ISSUE TITLE
Polymorphism - get name from child

### ISSUE THREAD

**Issue by akuznetsov032** [pdvrieze/xmlutil#93]
I have two xml requests:

```
<Request>
	<Version>2</Version>
	<TerminalTime>20220815234451</TerminalTime>
	<RequestType>BookDetails</RequestType>
	<BookDetails IncludeBookMarks="No" IpAddress="192.168.1.1">
		<Param Idx="StartDate">01.08.2021</Param>
		<Param Idx="EndDate">15.08.2021</Param>
	</BookDetails>
</Request>

```
```
<Request>
	<Version>2</Version>
	<TerminalTime>20220815234451</TerminalTime>
	<RequestType>SelectFavorite</RequestType>
	<SelectFavorite IpAddress="192.168.1.1">
		<Param Idx="FavoriteId">167283</Param>
		<Param Idx="EndDate">15.08.2021</Param>
	</BookDetails>
</Request>
```
Want to use Polymorphism for part of the request. Something like that:
```

@Serializable
data class ApiRequest(
    @XmlElement(true)
    @XmlSerialName("Version", "", "")
    val version: String,

    @XmlElement(true)
    @XmlSerialName("Version", "", "")
    val time: String,

    @XmlElement(true)
    @XmlSerialName("Version", "", "")
    val type: String,

    @XmlElement(true)
    @Polymorphic val requestData: Any
)

@Serializable
@XmlSerialName("BookDetails", "", "")
data class BookDetails(
    @XmlSerialName("IpAddress", "", "")
    val ipAddress: String,

    @XmlSerialName("IncludeBookMarks", "", "")
    val includeBookMarks: String,

    @XmlSerialName("Param", "", "")
    val params: MutableList<Param> = ArrayList()
)

@Serializable
@XmlSerialName("SelectFavorite", "", "")
data class SelectFavorite(
    @XmlSerialName("IpAddress", "", "")
    val ipAddress: String,

    @XmlSerialName("Param", "", "")
    val params: List<Param> = emptyList()
)

@Serializable
data class Param(
    @XmlSerialName("Idx", "", "")
    val idx: String,

    @XmlValue
    val value: String
)
```
serializers module is set and configured:
```
 XML(serializersModule = SerializersModule{
                    polymorphic(Any::class) {
                        subclass(BookDetails::class)
                        subclass(SelectFavorite::class)
                    }
                })  
```
Everything is worked, but not as I expected:
```
<Request>
	<Version>2</Version>
	<TerminalTime>20220815234451</TerminalTime>
	<RequestType>BookDetails</RequestType>
	<requestData type="com.akuznetsov.examlpe.BookDetails">
        ....
        </requestData>
</Request>
```

If I remove XmlElement from requestData, than got error:
 _Caused by: java.lang.IllegalArgumentException: Can't use arguments with defaults for serializable annotations yet_

Is it possible make Polymorphic field to get it's name from child?

**Comment by pdvrieze** [comment]
Without using a custom serializer for `Request` it is not possible to use arbitrary attributes/tags/fields to determine polymorphic subtypes. As far as the format deserializer is concerned there is no guarantee that the RequestType tag is present before the type for this tag. This is also how XML tends to handle this. If you need to be able to parse the tags as given the easiest way is to do it in two steps and first parse the tags as arbitrary xml nodes (maybe with a serialization adapter object that is only used for that) (supported by default if you use the right dom types - there should be some examples present), then you can parse the result as the specific subtype.

**Comment by pdvrieze** [comment]
Unfortunately there isn't really anything that can be done here as it would violate parsing. There are workarounds but that would involve 2-pass parsing of some sort.
